name: WebSockets Phoenix CI

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.2'
      - name: Fetch dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
